name:                little-scheme
version:             0.1.0.0
github:              "dannypsnl/little-scheme"
license:             MIT
author:              "dannypsnl"
maintainer:          "dannypsnl@gmail.com"
copyright:           "2020 dannypsnl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         https://github.com/dannypsnl/little-scheme

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2
- containers >= 0.6
- parsec >= 3.1
- directory >= 1.3.6
- filepath >= 1.4.2.1
- transformers >= 0.5.6.2
- haskeline >= 0.7.5.0

library:
  source-dirs: src

executables:
  little-scheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-scheme

tests:
  little-scheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-scheme
    - hspec
    - template-haskell
