name: Haskell CI

on: [push, pull_request]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      run: |
        cabal build
