name: Haskell CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.3']
        stack-version: [latest]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          stack build
      - run: |
          stack test
