name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    name: Test on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      run: |
        cabal build
