name: Haskell CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.3']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          stack-version: 'latest'
      - run: |
          stack build
      - run: |
          stack test
